apiVersion: v1
kind: Secret
metadata:
  name: my-azure-secret
  namespace: garden
type: Opaque
data:
  subscriptionID: xxx # Azure: Subscription ID
  tenantID: xxx       # Azure: App Registration -> Directory (tenant) ID
  clientID: xxx       # Azure: App Registration -> Application (client) ID
  clientSecret: xxx   # Azure: App Registration -> Certificate & Secrets -> Secret Value
