{{- if .Values.enabled }}
apiVersion: cert.gardener.cloud/v1alpha1
kind: Issuer
metadata:
  name: default-issuer
  namespace: garden
  annotations:
    cert.gardener.cloud/class: base-cert-class
spec:
  acme:
    autoRegistration: true
    email: {{ required "Value acme.email required for issuer" .Values.acme.email }}
    server: {{ required "Value acme.server required for issuer" .Values.acme.server }}
{{- end }}
