apiVersion: v2
dependencies:
- condition: utils-templates.enabled
  name: utils-templates
  repository: ""
- condition: terminal-controller-manager-application.enabled
  name: terminal-controller-manager-application
  repository: ""
- condition: terminal-controller-manager-runtime.enabled
  name: terminal-controller-manager-runtime
  repository: ""
deprecated: true
description: A Helm chart to deploy the terminal-controller-manager
name: gardener-webterminal
version: 0.38.0
