apiVersion: v1
kind: Secret
metadata:
  name: addons-base-values
  namespace: flux-system
type: Opaque
stringData:
  values.yaml: |-
    backups:
      {{- toYaml .Values.backups | nindent 6 }}
    vpa-crd:
      {{- toYaml (index .Values.addons "vpa-crd") | nindent 6 }}
