apiVersion: v1
kind: Secret
metadata:
  name: dnsprovider-base-values
  namespace: flux-system
type: Opaque
stringData:
  values.yaml: |-
    domains:
      - {{ include "global.domain" . }}
    provider: {{ required "Value domains.global.provider is required" .Values.domains.global.provider }}
    credentials:
      {{- toYaml (required "Value domains.global.credentials are required" .Values.domains.global.credentials) | nindent 6 }}
