---
apiVersion: v1
kind: Secret
metadata:
  name: extensions-base-values
  namespace: flux-system
type: Opaque
stringData:
  values.yaml: |-
    os-ubuntu:
      version: 1.38.0

    os-gardenlinux:
      version: 0.39.0

    os-coreos:
      version: 1.29.0

    provider-hcloud:
      version: 0.6.42
      admission:
        enabled: false

    provider-azure:
      version: 1.59.0
      admission:
        enabled: true
        split: false

    provider-openstack:
      version: 1.53.1
      admission:
        enabled: true

    networking-calico:
      version: 1.58.0

    shoot-cert-service:
      version: 1.57.0

    shoot-dns-service:
      version: 1.79.0
      admission:
        enabled: true
      values:
        dnsControllerManager:
          deploy: true
          configuration:
            cacheTtl: 300
            controllers: dnscontrollers,dnssources
            dnsPoolResyncPeriod: 30m
            serverPortHttp: 8080

    shoot-oidc-service:
      version: 0.37.0

    shoot-networking-filter:
      version: 0.28.0

    shoot-networking-problemdetector:
      version: 0.32.1

    shoot-rsyslog-relp:
      version: 0.12.0

    networking-cilium:
      version: 1.47.0

    provider-alicloud:
      version: 1.69.0
      admission:
        enabled: true

    provider-aws:
      version: 1.68.3
      admission:
        enabled: true

    provider-gcp:
      version: 1.50.0
      admission:
        enabled: true

    runtime-gvisor:
      version: 0.29.0

    backup-s3:
      version: 0.8.2

    shoot-flux:
      version: 0.25.0

    acl:
      version: 1.16.0
      admission:
        enabled: true

    image-rewriter:
      version: 0.9.0

    registry-cache:
      version: 0.21.0
      admission:
        enabled: true
