apiVersion: v2
dependencies:
- condition: utils-templates.enabled
  name: utils-templates
  repository: ""
deprecated: true
description: A Helm chart to deploy the terminal-controller-manager application related
  components
name: terminal-controller-manager-application
version: 0.37.0
