clusterIdentity: garden-cluster-identity
gardenlet:
  ingressDomain: internal

dashboard:
  image:
    repository: eu.gcr.io/gardener-project/gardener/dashboard
    tagOriginal:

domains:
  global:
    domain: "example.org"

backups:
  enabled: false

issuer:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
