apiVersion: v1
kind: Secret
metadata:
  name: gardenlet-values
  namespace: flux-system
type: Opaque
stringData:
  values.yaml: |-
    config:
      seedConfig:
        metadata:
          name: initial-seed
        taints:
          seed.gardener.cloud/protected: true
        spec:
          networks:
            nodes: 10.224.0.0/16
            pods: 10.244.0.0/16
            services: 10.0.0.0/16
            shootDefaults:
              pods: 100.100.0.0/16
              services: 100.101.0.0/16
          provider:
            region: germany-west-central
            type: azure
          settings:
            scheduling:
              visible: true
            excessCapacityReservation:
              enabled: false
            loadBalancerServices:
              externalTrafficPolicy: Local # azure
            verticalPodAutoscaler:
              enabled: true
