apiVersion: v1
kind: Secret
metadata:
  name: yake-config
  namespace: flux-system
type: Opaque
stringData:
  values.yaml: |
    clusterIdentity: garden-cluster-aks
    issuer:
      enabled: true

      acme:
        email: operations@aks-guide.okeanos.dev
        server: https://acme-v02.api.letsencrypt.org/directory

    domains:
      global: # means used for ingress, gardener defaultDomain and internalDomain
        domain: aks-guide.okeanos.dev
        provider: azure-dns
        credentials:
          subscriptionID: xxx   # Azure: Subscription ID
          tenantID: xxx         # Azure: App Registration -> Directory (tenant) ID
          clientID: xxx         # Azure: App Registration -> Application (client) ID
          clientSecret: xxx     # Azure: App Registration -> Certificate & Secrets -> Secret Value

    backups:
      enabled: false
