{{- range .Values.additionalSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
{{- if .data }}
data:
  {{- toYaml .data | nindent 2 }}
{{- else if .stringData }}
stringData:
  {{- toYaml .stringData | nindent 2 }}
{{- end }}
{{- end }}
