apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: garden-ca
  namespace: flux-system
spec:
  interval: 1m
  dependsOn:
    - name: cert-manager
  chart:
    spec:
      chart: gardener/gardener-ca
      sourceRef:
        kind: GitRepository
        name: 23ke
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: gardener-ca-base-values
      optional: false
